import React from "react";

const sizeClasses = {
  txtSatoshiRegular16WhiteA70087: "font-normal font-satoshi",
  txtChillaxMedium40: "font-chillax font-medium",
  txtSatoshiMedium19: "font-medium font-satoshi",
  txtSatoshiBlack27: "font-black font-satoshi",
  txtSatoshiRegular19: "font-normal font-satoshi",
  txtChillaxRegular60: "font-chillax font-normal",
  txtSatoshiMedium15: "font-medium font-satoshi",
  txtSatoshiRegular14: "font-normal font-satoshi",
  txtSatoshiMedium14IndigoA700: "font-medium font-satoshi",
  txtSatoshiRegular15: "font-normal font-satoshi",
  txtSatoshiMedium16: "font-medium font-satoshi",
  txtSatoshiMedium17: "font-medium font-satoshi",
  txtSatoshiBold1687: "font-bold font-satoshi",
  txtSatoshiRegular16: "font-normal font-satoshi",
  txtSatoshiMedium18: "font-medium font-satoshi",
  txtSatoshiBlack24: "font-black font-satoshi",
  txtSatoshiMedium14WhiteA700: "font-medium font-satoshi",
  txtSatoshiRegular17: "font-normal font-satoshi",
  txtSatoshiMedium11: "font-medium font-satoshi",
  txtSatoshiMedium12: "font-medium font-satoshi",
  txtSatoshiMedium17WhiteA700: "font-medium font-satoshi",
  txtSatoshiMedium13: "font-medium font-satoshi",
  txtSatoshiMedium14: "font-medium font-satoshi",
  txtSatoshiBlack20: "font-black font-satoshi",
  txtSatoshiRegular13: "font-normal font-satoshi",
  txtChillaxBold60: "font-bold font-chillax",
  txtSatoshiMedium186: "font-medium font-satoshi",
  txtSatoshiMedium14WhiteA70087: "font-medium font-satoshi",
  txtSatoshiMedium15Bluegray40001: "font-medium font-satoshi",
  txtSatoshiItalic12: "font-normal font-satoshi italic",
  txtChillaxSemibold20: "font-chillax font-semibold",
  txtSatoshiRegular19WhiteA70087: "font-normal font-satoshi",
  txtSatoshiMedium1674: "font-medium font-satoshi",
  txtSatoshiMedium17Gray900: "font-medium font-satoshi",
  txtSatoshiMedium17IndigoA700: "font-medium font-satoshi",
  txtSatoshiBold20WhiteA70087: "font-bold font-satoshi",
  txtSatoshiMedium13Gray100: "font-medium font-satoshi",
  txtSatoshiLight27: "font-light font-satoshi",
  txtChillaxSemibold27: "font-chillax font-semibold",
  txtSatoshiMedium15GreenA700: "font-medium font-satoshi",
  txtSatoshiBlack372: "font-black font-satoshi",
  txtSatoshiBold1459: "font-bold font-satoshi",
  txtSatoshiMedium15WhiteA7007e: "font-medium font-satoshi",
  txtSatoshiMedium16WhiteA700cc: "font-medium font-satoshi",
  txtSatoshiRegular159: "font-normal font-satoshi",
  txtSatoshiMedium13IndigoA700: "font-medium font-satoshi",
  txtSatoshiBold22IndigoA700: "font-bold font-satoshi",
  txtChillaxSemibold33: "font-chillax font-semibold",
  txtSatoshiMedium16Lightblue800: "font-medium font-satoshi",
  txtChillaxRegular36: "font-chillax font-normal",
  txtSatoshiMedium12WhiteA700: "font-medium font-satoshi",
  txtSatoshiBold19IndigoA700: "font-bold font-satoshi",
  txtSatoshiRegular17WhiteA70087: "font-normal font-satoshi",
  txtChillaxRegular41: "font-chillax font-normal",
  txtSatoshiBold19: "font-bold font-satoshi",
  txtSatoshiRegular14WhiteA70090: "font-normal font-satoshi",
  txtChillaxMedium60: "font-chillax font-medium",
  txtChillaxSemibold35: "font-chillax font-semibold",
  txtChillaxSemibold36: "font-chillax font-semibold",
  txtChillaxBold47: "font-bold font-chillax",
  txtSatoshiMedium16WhiteA70087: "font-medium font-satoshi",
  txtSatoshiBold13: "font-bold font-satoshi",
  txtSatoshiMedium159: "font-medium font-satoshi",
  txtSatoshiBold17: "font-bold font-satoshi",
  txtSatoshiRegular17WhiteA7007e: "font-normal font-satoshi",
  txtChillaxBold60IndigoA700: "font-bold font-chillax",
  txtSatoshiBold18: "font-bold font-satoshi",
  txtSatoshiBold15: "font-bold font-satoshi",
  txtSatoshiBold16: "font-bold font-satoshi",
  txtSatoshiMedium16WhiteA700: "font-medium font-satoshi",
  txtSatoshiMedium19WhiteA70075: "font-medium font-satoshi",
  txtSatoshiBold20: "font-bold font-satoshi",
  txtSatoshiBold21: "font-bold font-satoshi",
  txtChillaxMedium17: "font-chillax font-medium",
  txtSatoshiBold20WhiteA700: "font-bold font-satoshi",
  txtSatoshiMedium19WhiteA7007e: "font-medium font-satoshi",
  txtSatoshiBlack16: "font-black font-satoshi",
  txtSatoshiBlack17: "font-black font-satoshi",
  txtSatoshiMedium19WhiteA70090: "font-medium font-satoshi",
  txtSatoshiMedium26: "font-medium font-satoshi",
  txtSatoshiMedium20Gray90087: "font-medium font-satoshi",
  txtSatoshiBold25: "font-bold font-satoshi",
  txtSatoshiBold22: "font-bold font-satoshi",
  txtSatoshiMedium16WhiteA70099: "font-medium font-satoshi",
  txtSatoshiBold23: "font-bold font-satoshi",
  txtSatoshiMedium15IndigoA700: "font-medium font-satoshi",
  txtSatoshiBold1674: "font-bold font-satoshi",
  txtSatoshiBold17IndigoA700: "font-bold font-satoshi",
  txtSatoshiBold26: "font-bold font-satoshi",
  txtSatoshiMedium19WhiteA70087: "font-medium font-satoshi",
  txtSatoshiItalic20: "font-normal font-satoshi italic",
  txtSatoshiMedium20: "font-medium font-satoshi",
  txtSatoshiMedium14WhiteA70075: "font-medium font-satoshi",
  txtSatoshiBold30: "font-bold font-satoshi",
  txtChillaxRegular17: "font-chillax font-normal",
  txtSatoshiRegular17IndigoA700: "font-normal font-satoshi",
};

const Text = ({ children, className = "", size, as, ...restProps }) => {
  const Component = as || "p";

  return (
    <Component
      className={`text-left ${className} ${size && sizeClasses[size]}`}
      {...restProps}
    >
      {children}
    </Component>
  );
};

export { Text };
