import React from "react";
import { Link } from "react-router-dom";
const Home = () => {
  return (
    <div className="dhiwise-navigation">
      <h1>Homepage</h1>
      <p className="headline">
        This project was generated By{" "}
        <a href="https://www.dhiwise.com">Dhiwise</a>. Quickly use below links
        to navigate through all pages.
      </p>
      <ul>
        <li>
          <Link to="/rockitlylandingpage">Rockitlylandingpage</Link>
        </li>
        <li>
          <Link to="/rockitlymarketplaceone">RockitlymarketplaceOne</Link>
        </li>
        <li>
          <Link to="/p2ptrading">P2ptrading</Link>
        </li>
        <li>
          <Link to="/rockitlyabout">Rockitlyabout</Link>
        </li>
        <li>
          <Link to="/contact">Contact</Link>
        </li>
        <li>
          <Link to="/termsofuse">Termsofuse</Link>
        </li>
        <li>
          <Link to="/rockitlytestimonials">Rockitlytestimonials</Link>
        </li>
        <li>
          <Link to="/rockitlyescrowsystem">Rockitlyescrowsystem</Link>
        </li>
        <li>
          <Link to="/rockitlylogin">Rockitlylogin</Link>
        </li>
        <li>
          <Link to="/rockitlysignup">Rockitlysignup</Link>
        </li>
        <li>
          <Link to="/buyp2ptradinglisting">Buyp2ptradinglisting</Link>
        </li>
        <li>
          <Link to="/buyp2ptradingdetails">Buyp2ptradingdetails</Link>
        </li>
        <li>
          <Link to="/sellp2ptradinglisting">Sellp2ptradinglisting</Link>
        </li>
        <li>
          <Link to="/sellp2ptradingdetails">Sellp2ptradingdetails</Link>
        </li>
        <li>
          <Link to="/rockitlymarketplace">Rockitlymarketplace</Link>
        </li>
        <li>
          <Link to="/dashboardtradehistory">Dashboardtradehistory</Link>
        </li>
        <li>
          <Link to="/dashboardtradehistoryone">DashboardtradehistoryOne</Link>
        </li>
        <li>
          <Link to="/dashboardrecenttradepartner">
            Dashboardrecenttradepartner
          </Link>
        </li>
        <li>
          <Link to="/dashboardmyoffers">Dashboardmyoffers</Link>
        </li>
        <li>
          <Link to="/dashboardfavoriteoffers">Dashboardfavoriteoffers</Link>
        </li>
        <li>
          <Link to="/dashboardtradestatistics">Dashboardtradestatistics</Link>
        </li>
        <li>
          <Link to="/dashboardtraderprogrambadges">
            Dashboardtraderprogrambadges
          </Link>
        </li>
        <li>
          <Link to="/dashboardshareprofile">Dashboardshareprofile</Link>
        </li>
        <li>
          <Link to="/accountsettingprofile">Accountsettingprofile</Link>
        </li>
        <li>
          <Link to="/accountsettinglocalization">
            Accountsettinglocalization
          </Link>
        </li>
        <li>
          <Link to="/accountsettingmessenger">Accountsettingmessenger</Link>
        </li>
        <li>
          <Link to="/accountsettingsecurity">Accountsettingsecurity</Link>
        </li>
        <li>
          <Link to="/accountsettingpaymentmethods">
            Accountsettingpaymentmethods
          </Link>
        </li>
        <li>
          <Link to="/accountsettingdeveloper">Accountsettingdeveloper</Link>
        </li>
        <li>
          <Link to="/accountsettingappsandweb">Accountsettingappsandweb</Link>
        </li>
        <li>
          <Link to="/accountsettingquestions">Accountsettingquestions</Link>
        </li>
      </ul>
    </div>
  );
};
export default Home;
